/**
 * A note as the folder tree dresses it — its colour and icon from `folders`
 * (`lm/folders`' `look`) — for any view that lists notes (`calendar`, `kanban`), so a note
 * reads as the same note wherever it appears, as `markdown`'s links already make it.
 *
 * Styles are inline, not classes: this file is compiled into several plugins, and each
 * plugin's Tailwind build scans only its own `src/`, so a prefixed class here would be
 * generated by none of them.
 */

import { useEffect, useState } from "react";
import type { CSSProperties, ReactElement } from "react";

import type { Folders, NoteLook } from "plugin:folders";

/** The part of `lm/folders` a view reads. */
export type Looks = Pick<Folders, "look" | "onLookChange">;

/** A note's look, when it has anything to show. */
export function lookOf(looks: Looks | undefined, id: string): NoteLook | undefined {
  const look = looks?.look(id);
  return look && (look.background || look.color || look.icon !== undefined) ? look : undefined;
}

/** The note's own colours, for a chip; `undefined` leaves the view's default. */
export function lookStyle(look: NoteLook | undefined): CSSProperties | undefined {
  if (!look || (!look.background && !look.color)) return undefined;
  return {
    ...(look.background ? { background: look.background } : {}),
    ...(look.color ? { color: look.color } : {}),
  };
}

/** Re-render whenever any note's look may have changed. */
export function useLookChanges(looks: Looks | undefined): void {
  const [, setRevision] = useState(0);
  useEffect(() => looks?.onLookChange(() => setRevision((value) => value + 1)), [looks]);
}

const ROW: CSSProperties = { display: "flex", minWidth: 0, alignItems: "center", gap: "0.25rem" };
const ICON: CSSProperties = { display: "inline-flex", flexShrink: 0, width: "1em", height: "1em" };
const TEXT: CSSProperties = { minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" };

/** A note's title with its icon, as the tree shows it. */
export function NoteLabel({ title, look }: { readonly title: string; readonly look: NoteLook | undefined }): ReactElement {
  return (
    <span style={ROW}>
      {look?.icon !== undefined && (
        <span aria-hidden="true" style={ICON}>
          {look.icon}
        </span>
      )}
      <span style={TEXT}>{title}</span>
    </span>
  );
}
