/**
 * GENERATED by web/scripts/gen-manifest.mjs from schema/manifest.schema.json. Do not edit.
 */

/** The `@kernel` contract version (`x-kernel-version`). The server's `KERNEL_VERSION` is generated from the same line. */
export const MANIFEST_KERNEL_VERSION = "3.0.0";

export interface PluginFrontend {
  /** Path inside the package, e.g. `frontend/index.mjs`. */
  readonly module: string;
  /** Linked on activation (SPEC §6.4). */
  readonly style?: string;
}

export interface PluginCapabilities {
  /** Gates the server-side document host functions (SPEC §6.2). Unknown strings are refused rather than read as "no access". */
  readonly documents?: readonly ("read" | "write")[];
  /** Outbound HTTP, per declared hosts. No wildcards. */
  readonly http?: HttpCapability;
  /** Native-bridge notifications (frontend-side, SPEC §7). */
  readonly notifications?: boolean;
  /** Unauthenticated routes under `/api/plugins/<id>`, shown at install. Each must also appear in `backend.routes`. */
  readonly "public-routes"?: readonly (string)[];
}

export interface HttpCapability {
  /** Bare host names, matched exactly. */
  readonly hosts: readonly (string)[];
}

export interface PluginConfigField {
  /** `string` | `number` | `boolean` | `select`. */
  readonly type: "string" | "number" | "boolean" | "select";
  /** Write-only in the admin UI, encrypted at rest (SPEC §6.2). */
  readonly secret?: boolean;
  readonly label?: string;
  readonly description?: string;
  /** Shown as the field's placeholder and used when nothing is set. Never applied to a secret. */
  readonly default?: unknown;
  readonly required?: boolean;
  /** For `select`. */
  readonly options?: readonly (string)[];
}

export interface PluginBackend {
  /** Path inside the package, conventionally `backend.wasm`. The only file outside `frontend/**` the installer extracts. */
  readonly module: string;
  /** Document hooks (SPEC §6.3). */
  readonly hooks?: readonly ("document.created" | "document.changed" | "document.deleted")[];
  /** Five-field UTC cron expressions (SPEC §6.3). */
  readonly cron?: readonly (string)[];
  /** `"POST /webhook"`: method and path, space separated. */
  readonly routes?: readonly (string)[];
  /** Server-bus events delivered to `lm_event`, namespaced (`other-plugin:something`). */
  readonly events?: readonly (string)[];
  /** Functions this backend's `lm_call` answers for plugins that depend on it (HOST-ABI.md §3.10). A call to a name not listed is refused; `input`/`output` shapes are checked at the boundary. */
  readonly exports?: Readonly<Record<string, BackendExport>>;
}

export interface BackendExport {
  /** Shape JSON (`@kernel` `s.*`, serialized) the payload must fit. Absent: anything. */
  readonly input?: unknown;
  /** Shape JSON the returned value must fit. Absent: anything. */
  readonly output?: unknown;
  readonly description?: string;
}

/** A plugin's manifest.json (SPEC §6.2). The one source for the Rust and TypeScript manifest types and validators: `node web/scripts/gen-manifest.mjs` writes both, and `--check` fails when either is stale. */
export interface PluginManifest {
  /** `^[a-z0-9][a-z0-9-]{0,63}$`, also the URL segment under `/plugins/`. */
  readonly id: string;
  /** `1.2.3` with an optional prerelease/build tail. */
  readonly version: string;
  /** Semver range against the `@kernel` contract version. */
  readonly kernel: string;
  /** Plugin id → semver range. Each one loads before this plugin, and this plugin is skipped when one is missing, out of range or failed. Its exports are importable as `plugin:<id>`. */
  readonly dependencies?: Readonly<Record<string, string>>;
  /** Like `dependencies`, but this plugin still loads without them. Reach one through `kernel.plugins.optional(id)`, never a static import. */
  readonly optionalDependencies?: Readonly<Record<string, string>>;
  /** `<id>@<version>`: this plugin stands in for another one at that API version. `plugin:<id>` resolves to whichever of the two is enabled; only one may be. */
  readonly provides?: string;
  /** Blessed runtime-layer libraries and their ranges (SPEC §6.4). */
  readonly peerLibraries?: Readonly<Record<string, string>>;
  /** The frontend half. */
  readonly frontend?: PluginFrontend;
  /** The capability set a manifest requests (SPEC §6.2). */
  readonly capabilities?: PluginCapabilities;
  /** The admin-config schema (SPEC §6.2). Values live in `plugin_config`; this is only their declaration. */
  readonly config?: Readonly<Record<string, PluginConfigField>>;
  /** The backend half: module, hooks, cron, routes, event subscriptions. */
  readonly backend?: PluginBackend;
  /** Human metadata; never load-bearing. */
  readonly name?: string;
  /** Human metadata; never load-bearing. */
  readonly description?: string;
  /** Human metadata; never load-bearing. */
  readonly author?: string;
  /** Human metadata; never load-bearing. */
  readonly license?: string;
  /** `x-*` keys are the author's own metadata, passed through untouched. */
  readonly [extension: `x-${string}`]: unknown;
}

/** The schema itself, for `validateManifest`. */
export const MANIFEST_SCHEMA: ManifestSchemaNode = {
  "x-removed": {
    "consumes": "was removed in @kernel 3.0: import what you use from `plugin:<id>` and list the plugin under `dependencies`",
    "hot": "was removed in @kernel 3.0: every plugin change reloads the app",
    "x-defines": "was removed in @kernel 2.0: export a registration function (`addItem`) instead"
  },
  "type": "object",
  "required": [
    "id",
    "version",
    "kernel"
  ],
  "properties": {
    "id": {
      "type": "string",
      "format": "plugin-id"
    },
    "version": {
      "type": "string",
      "format": "semver"
    },
    "kernel": {
      "type": "string",
      "format": "semver-range"
    },
    "dependencies": {
      "type": "object",
      "propertyNames": {
        "format": "plugin-id"
      },
      "additionalProperties": {
        "type": "string",
        "format": "semver-range"
      }
    },
    "optionalDependencies": {
      "type": "object",
      "propertyNames": {
        "format": "plugin-id"
      },
      "additionalProperties": {
        "type": "string",
        "format": "semver-range"
      }
    },
    "provides": {
      "type": "string",
      "format": "plugin-ref"
    },
    "peerLibraries": {
      "type": "object",
      "additionalProperties": {
        "type": "string",
        "format": "semver-range"
      }
    },
    "frontend": {
      "$ref": "#/$defs/PluginFrontend"
    },
    "capabilities": {
      "$ref": "#/$defs/PluginCapabilities"
    },
    "config": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/$defs/PluginConfigField"
      }
    },
    "backend": {
      "$ref": "#/$defs/PluginBackend"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "author": {
      "type": "string"
    },
    "license": {
      "type": "string"
    }
  },
  "$defs": {
    "PluginFrontend": {
      "type": "object",
      "required": [
        "module"
      ],
      "properties": {
        "module": {
          "type": "string",
          "format": "relative-path"
        },
        "style": {
          "type": "string",
          "format": "relative-path"
        }
      }
    },
    "PluginCapabilities": {
      "type": "object",
      "properties": {
        "documents": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "read",
              "write"
            ]
          }
        },
        "http": {
          "$ref": "#/$defs/HttpCapability"
        },
        "notifications": {
          "type": "boolean"
        },
        "public-routes": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "HttpCapability": {
      "type": "object",
      "properties": {
        "hosts": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "PluginConfigField": {
      "type": "object",
      "required": [
        "type"
      ],
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "string",
            "number",
            "boolean",
            "select"
          ]
        },
        "secret": {
          "type": "boolean"
        },
        "label": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "default": {},
        "required": {
          "type": "boolean"
        },
        "options": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "PluginBackend": {
      "type": "object",
      "x-removed": {
        "calls": "was removed in @kernel 3.0: list the callee under the manifest's `dependencies`"
      },
      "required": [
        "module"
      ],
      "properties": {
        "module": {
          "type": "string",
          "format": "relative-path"
        },
        "hooks": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "document.created",
              "document.changed",
              "document.deleted"
            ]
          }
        },
        "cron": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "routes": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "events": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "exports": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/$defs/BackendExport"
          }
        }
      }
    },
    "BackendExport": {
      "type": "object",
      "properties": {
        "input": {},
        "output": {},
        "description": {
          "type": "string"
        }
      }
    }
  }
};

/** The subset of JSON Schema the validators interpret. */
export interface ManifestSchemaNode {
  readonly $ref?: string;
  readonly type?: "object" | "array" | "string" | "number" | "integer" | "boolean";
  readonly required?: readonly string[];
  readonly properties?: Readonly<Record<string, ManifestSchemaNode>>;
  readonly additionalProperties?: ManifestSchemaNode | boolean;
  readonly propertyNames?: { readonly format?: string };
  readonly items?: ManifestSchemaNode;
  readonly enum?: readonly unknown[];
  readonly format?: string;
  readonly minimum?: number;
  readonly $defs?: Readonly<Record<string, ManifestSchemaNode>>;
  /** Fields a manifest may no longer carry, each with the message that says what replaced it. */
  readonly "x-removed"?: Readonly<Record<string, string>>;
}
