pub mod auth;
pub mod changes;
pub mod config;
pub mod db;
pub mod docstore;
pub mod domain;
pub mod error;
pub mod feed;
pub mod load;
pub mod manifest_schema;
pub mod manifest_types;
pub mod pluginhost;
pub mod plugininstall;
pub mod plugins;
pub mod query_index;
pub mod routes;
pub mod state;
pub mod telemetry;

pub const VERSION: &str = env!("CARGO_PKG_VERSION");
