//! GENERATED by web/scripts/gen-manifest.mjs from schema/manifest.schema.json. Do not edit.
//!
//! The manifest's serde types. Methods live in `plugins.rs`; validation is
//! `manifest_schema.rs`, an interpreter over the same schema.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

/// The `@kernel` contract version this server implements (`x-kernel-version`). The web
/// bundle's `KERNEL_API_VERSION` is generated from the same line.
pub const KERNEL_VERSION: &str = "3.1.0";

/// A plugin's manifest.json (SPEC §6.2). The one source for the Rust and TypeScript manifest types and validators: `node web/scripts/gen-manifest.mjs` writes both, and `--check` fails when either is stale.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PluginManifest {
    /// `^[a-z0-9][a-z0-9-]{0,63}$`, also the URL segment under `/plugins/`.
    pub id: String,
    /// `1.2.3` with an optional prerelease/build tail.
    pub version: String,
    /// Semver range against the `@kernel` contract version.
    pub kernel: String,
    /// Plugin id → semver range. Each one loads before this plugin, and this plugin is skipped when one is missing, out of range or failed. Its exports are importable as `plugin:<id>`.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub dependencies: BTreeMap<String, String>,
    /// Like `dependencies`, but this plugin still loads without them. Reach one through `kernel.plugins.optional(id)`, never a static import.
    #[serde(
        default,
        rename = "optionalDependencies",
        skip_serializing_if = "BTreeMap::is_empty"
    )]
    pub optional_dependencies: BTreeMap<String, String>,
    /// `<id>@<version>`: this plugin stands in for another one at that API version. `plugin:<id>` resolves to whichever of the two is enabled; only one may be.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provides: Option<String>,
    /// Blessed runtime-layer libraries and their ranges (SPEC §6.4).
    #[serde(
        default,
        rename = "peerLibraries",
        skip_serializing_if = "BTreeMap::is_empty"
    )]
    pub peer_libraries: BTreeMap<String, String>,
    /// The frontend half.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub frontend: Option<PluginFrontend>,
    /// The capability set a manifest requests (SPEC §6.2).
    #[serde(default, skip_serializing_if = "PluginCapabilities::is_empty")]
    pub capabilities: PluginCapabilities,
    /// The admin-config schema (SPEC §6.2). Values live in `plugin_config`; this is only their declaration.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub config: BTreeMap<String, ConfigField>,
    /// The backend half: module, hooks, cron, routes, event subscriptions.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub backend: Option<PluginBackend>,
    /// Human metadata; never load-bearing.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Human metadata; never load-bearing.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Human metadata; never load-bearing.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub author: Option<String>,
    /// Human metadata; never load-bearing.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub license: Option<String>,
    /// Everything else in the file, passed through untouched (`x-*` keys, and anything a
    /// newer server understands that this one does not).
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PluginFrontend {
    /// Path inside the package, e.g. `frontend/index.mjs`.
    pub module: String,
    /// Linked on activation (SPEC §6.4).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub style: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct PluginCapabilities {
    /// Gates the server-side document host functions (SPEC §6.2). Unknown strings are refused rather than read as "no access".
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub documents: Vec<String>,
    /// Outbound HTTP, per declared hosts. No wildcards.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub http: Option<HttpCapability>,
    /// Native-bridge notifications (frontend-side, SPEC §7).
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub notifications: bool,
    /// Unauthenticated routes under `/api/plugins/<id>`, shown at install. Each must also appear in `backend.routes`.
    #[serde(
        default,
        rename = "public-routes",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub public_routes: Vec<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct HttpCapability {
    /// Bare host names, matched exactly.
    #[serde(default)]
    pub hosts: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ConfigField {
    /// `string` | `number` | `boolean` | `select`.
    #[serde(rename = "type")]
    pub kind: String,
    /// Write-only in the admin UI, encrypted at rest (SPEC §6.2).
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub secret: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Shown as the field's placeholder and used when nothing is set. Never applied to a secret.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub default: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub required: bool,
    /// For `select`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub options: Vec<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct PluginBackend {
    /// Path inside the package, conventionally `backend.wasm`. The only file outside `frontend/**` the installer extracts.
    pub module: String,
    /// Document hooks (SPEC §6.3).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub hooks: Vec<String>,
    /// Five-field UTC cron expressions (SPEC §6.3).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub cron: Vec<String>,
    /// `"POST /webhook"`: method and path, space separated.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub routes: Vec<String>,
    /// Server-bus events delivered to `ddd_event`, namespaced (`other-plugin:something`).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub events: Vec<String>,
    /// Functions this backend's `ddd_call` answers for plugins that depend on it (HOST-ABI.md §3.10). A call to a name not listed is refused; `input`/`output` shapes are checked at the boundary.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub exports: BTreeMap<String, BackendExport>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BackendExport {
    /// Shape JSON (`@kernel` `s.*`, serialized) the payload must fit. Absent: anything.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub input: Option<serde_json::Value>,
    /// Shape JSON the returned value must fit. Absent: anything.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}
