//! GENERATED by web/scripts/gen-manifest.mjs from schema/manifest.schema.json. Do not edit.
//!
//! The manifest's serde types. Methods live in `plugins.rs`; validation is
//! `manifest_schema.rs`, an interpreter over the same schema.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

/// The `@kernel` contract version this server implements (`x-kernel-version`). The web
/// bundle's `KERNEL_API_VERSION` is generated from the same line.
pub const KERNEL_VERSION: &str = "2.1.0";

/// A plugin's manifest.json (SPEC §6.2). The one source for the Rust and TypeScript manifest types and validators: `node web/scripts/gen-manifest.mjs` writes both, and `--check` fails when either is stale.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PluginManifest {
    /// `^[a-z0-9][a-z0-9-]{0,63}$`, also the URL segment under `/plugins/`.
    pub id: String,
    /// `1.2.3` with an optional prerelease/build tail.
    pub version: String,
    /// Semver range against the `@kernel` contract version.
    pub kernel: String,
    /// Blessed runtime-layer libraries and their ranges (SPEC §6.4).
    #[serde(
        default,
        rename = "peerLibraries",
        skip_serializing_if = "BTreeMap::is_empty"
    )]
    pub peer_libraries: BTreeMap<String, String>,
    /// The frontend half.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub frontend: Option<PluginFrontend>,
    /// The capability set a manifest requests (SPEC §6.2).
    #[serde(default, skip_serializing_if = "PluginCapabilities::is_empty")]
    pub capabilities: PluginCapabilities,
    /// The admin-config schema (SPEC §6.2). Values live in `plugin_config`; this is only their declaration.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub config: BTreeMap<String, ConfigField>,
    /// The backend half: module, hooks, cron, routes, event subscriptions.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub backend: Option<PluginBackend>,
    /// Port name → the protocol this plugin provides there, at the exact version it implements (PLUGIN-PROTOCOLS §4).
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub provides: BTreeMap<String, ProvidedPort>,
    /// Port name → the protocol this plugin consumes there, as a semver range (PLUGIN-PROTOCOLS §4).
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub consumes: BTreeMap<String, ConsumedPort>,
    /// A promise that the kernel's retraction plus this plugin's own `deactivate()` leave nothing behind, so wiring changes that touch it apply without a reload (PLUGIN-PROTOCOLS §6c).
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub hot: bool,
    /// Human metadata; never load-bearing.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Human metadata; never load-bearing.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Human metadata; never load-bearing.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub author: Option<String>,
    /// Human metadata; never load-bearing.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub license: Option<String>,
    /// Everything else in the file, passed through untouched (`x-*` keys, and anything a
    /// newer server understands that this one does not).
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PluginFrontend {
    /// Path inside the package, e.g. `frontend/index.mjs`.
    pub module: String,
    /// Linked on activation (SPEC §6.4).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub style: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct PluginCapabilities {
    /// Gates the server-side document host functions (SPEC §6.2). Unknown strings are refused rather than read as "no access".
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub documents: Vec<String>,
    /// Outbound HTTP, per declared hosts. No wildcards.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub http: Option<HttpCapability>,
    /// Native-bridge notifications (frontend-side, SPEC §7).
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub notifications: bool,
    /// Unauthenticated routes under `/api/plugins/<id>`, shown at install. Each must also appear in `backend.routes`.
    #[serde(
        default,
        rename = "public-routes",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub public_routes: Vec<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct HttpCapability {
    /// Bare host names, matched exactly.
    #[serde(default)]
    pub hosts: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ConfigField {
    /// `string` | `number` | `boolean` | `select`.
    #[serde(rename = "type")]
    pub kind: String,
    /// Write-only in the admin UI, encrypted at rest (SPEC §6.2).
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub secret: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Shown as the field's placeholder and used when nothing is set. Never applied to a secret.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub default: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub required: bool,
    /// For `select`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub options: Vec<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct PluginBackend {
    /// Path inside the package, conventionally `backend.wasm`. The only file outside `frontend/**` the installer extracts.
    pub module: String,
    /// Document hooks (SPEC §6.3).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub hooks: Vec<String>,
    /// Five-field UTC cron expressions (SPEC §6.3).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub cron: Vec<String>,
    /// `"POST /webhook"`: method and path, space separated.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub routes: Vec<String>,
    /// Server-bus events delivered to `lm_event`, namespaced (`other-plugin:something`).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub events: Vec<String>,
    /// Plugin ids whose backend `lm_call` this half may reach through `call_plugin` (HOST-ABI.md §3.10). Replaces the `dependencies` allowlist removed in `@kernel` 2.0.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub calls: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ProvidedPort {
    /// `<publisher>/<name>@<version>`: the exact version this port implements, in full.
    pub protocol: String,
    /// Default-seat hint for slot ports: seats follow it, then plugin id, until someone edits the wiring. Wiring order always wins.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub order: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ConsumedPort {
    /// `<publisher>/<name>@<range>`, e.g. `lm/router@^1.0`.
    pub protocol: String,
    /// The protocol's keys this port uses. The type check asks only for these, and a service handle refuses any other key.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub needs: Option<Vec<String>>,
    /// A service port that may stay unbound: the plugin still activates and `use()` returns `undefined`.
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub optional: bool,
    /// A slot host that shows exactly one contributor sets `1`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub seats: Option<u32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}
